# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [2]:
import numpy as np 
arr1=np.random.randint(1,20,(5,5))

In [3]:
arr1

array([[16,  7,  8, 10, 10],
       [14,  7,  4,  8, 15],
       [18, 19,  6, 13, 15],
       [18,  1, 13,  7, 18],
       [12,  2,  9, 10, 13]], dtype=int32)

In [4]:
arr1[:,2]=1

In [5]:
arr1

array([[16,  7,  1, 10, 10],
       [14,  7,  1,  8, 15],
       [18, 19,  1, 13, 15],
       [18,  1,  1,  7, 18],
       [12,  2,  1, 10, 13]], dtype=int32)

In [6]:
arr2=np.linspace(1,16,1)

In [8]:
arr2=np.arange(1,17,1)

In [9]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [13]:
arr2=arr2.reshape(4,4)

In [14]:
#replace the diagonal element with 0 

np.fill_diagonal(arr2,0)

In [15]:
arr2

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [16]:
arr3=np.arange(1,37,1).reshape(6,6)

In [17]:
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [19]:
arr3[2:5,1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [21]:
arr4=np.random.randint(1,100,size=(5,5))

In [22]:
arr4

array([[ 9, 12, 93,  3, 15],
       [20, 52, 45, 55, 70],
       [52, 90, 44, 38, 96],
       [30, 66, 32,  4, 71],
       [65, 64, 37, 33, 61]], dtype=int32)

In [23]:
arr5=np.random.randint(1,50,size=(5,5))

In [24]:
arr5

array([[49, 14,  4, 16, 22],
       [16, 16, 49, 43, 27],
       [28, 27, 20, 49, 34],
       [35,  1, 44, 27, 13],
       [46, 20, 42, 37, 14]], dtype=int32)

In [25]:
top=arr5[0,:]
left=arr5[:,0]
right=arr5[:,4]
bottom=arr5[4,:]

In [26]:
border_elements=np.concatenate((top,left,bottom,right))

In [28]:
border_elements

array([49, 14,  4, 16, 22, 49, 16, 28, 35, 46, 46, 20, 42, 37, 14, 22, 27,
       34, 13, 14], dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [31]:
arr6=np.random.randint(1,13,size=(3,4))
arr7=np.random.randint(1,20,size=(3,4))

In [32]:
arr6,arr7

(array([[12,  8,  8,  6],
        [ 9,  2,  8,  8],
        [10, 12,  1,  3]], dtype=int32),
 array([[ 5, 12,  6, 17],
        [11, 15, 10, 17],
        [11, 11, 18,  9]], dtype=int32))

In [33]:
arr6+arr7

array([[17, 20, 14, 23],
       [20, 17, 18, 25],
       [21, 23, 19, 12]], dtype=int32)

In [34]:
arr6*arr7

array([[ 60,  96,  48, 102],
       [ 99,  30,  80, 136],
       [110, 132,  18,  27]], dtype=int32)

In [35]:
arr6/arr7

array([[2.4       , 0.66666667, 1.33333333, 0.35294118],
       [0.81818182, 0.13333333, 0.8       , 0.47058824],
       [0.90909091, 1.09090909, 0.05555556, 0.33333333]])

In [36]:
arr8=np.random.randint(1,20,size=(3,4))

In [37]:
arr8

array([[15,  7, 11, 19],
       [18, 14,  9, 18],
       [12, 15, 19,  1]], dtype=int32)

In [38]:
sum=0
for i in arr8:
    sum=sum+i
print(sum)

[45 36 39 38]

In [39]:
sum=0
for i in arr8:
    for j in i:
        sum=sum+j
print(sum)

158

In [40]:
arr9=np.arange(1,17).reshape(4,4)

In [41]:
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
row_sum=np.sum(arr9,axis=1)

In [43]:
row_sum

array([10, 26, 42, 58])

In [44]:
col_sum=np.sum(arr9,axis=0)

In [45]:
col_sum

array([28, 32, 36, 40])

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [46]:
arr10=np.random.randint(1,25,size=(5,5))

In [47]:
arr10

array([[ 4,  9, 10, 17,  4],
       [15, 14,  8, 21, 15],
       [22, 10,  2, 23, 13],
       [ 9, 18,  4, 24, 19],
       [21, 23, 17,  7,  1]], dtype=int32)

In [49]:
arr_mean=np.mean(arr10)
arr_dev=np.std(arr10)
arr_var=np.var(arr10)
arr_med=np.median(arr10)

In [50]:
arr_mean,arr_med,arr_dev,arr_var

(np.float64(13.2),
 np.float64(14.0),
 np.float64(7.0710678118654755),
 np.float64(50.0))

In [52]:
arr11=np.arange(1,10).reshape(3,3)
arr11_mean=np.mean(arr11)
arr11_std=np.std(arr11)

normalized_array=(arr11-arr11_mean)/arr11_std #z-score

print(normalized_array)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [53]:
arr12=np.random.randint(1,9,size=(3,3))

In [54]:
arr12

array([[5, 2, 4],
       [2, 5, 2],
       [2, 4, 6]], dtype=int32)

In [55]:
arr12+[1,2,3]

array([[6, 4, 7],
       [3, 7, 5],
       [3, 6, 9]])


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [61]:
arr13=np.random.randint(1,10,size=(3,3))

In [62]:
arr13

array([[8, 6, 6],
       [9, 5, 4],
       [7, 6, 7]], dtype=int32)

In [63]:
determinant=np.linalg.det(arr13)
inverse=np.linalg.inv(arr13)
eigenvalues=np.linalg.eigvals(arr13)

In [64]:
determinant,inverse,eigenvalues

(np.float64(-7.9999999999999805),
 array([[-1.375,  0.75 ,  0.75 ],
        [ 4.375, -1.75 , -2.75 ],
        [-2.375,  0.75 ,  1.75 ]]),
 array([19.4121138, -0.4121138,  1.       ]))

In [65]:
arr14=np.random.randint(1,6,size=(2,3))
arr15=np.random.randint(1,10,size=(3,3))

multiplication=np.matmul(arr14,arr15)
print(multiplication)

[[26 17 34]
 [45 27 60]]

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [66]:
arr16=np.random.randint(1,10,size=(5,5))

In [67]:
flattened=arr16.flatten()

In [68]:
flattened

array([2, 8, 3, 9, 5, 5, 5, 5, 7, 8, 6, 1, 3, 8, 1, 1, 6, 3, 2, 2, 8, 3,
       1, 9, 1], dtype=int32)

In [69]:
flattened.reshape(5,5)

array([[2, 8, 3, 9, 5],
       [5, 5, 5, 7, 8],
       [6, 1, 3, 8, 1],
       [1, 6, 3, 2, 2],
       [8, 3, 1, 9, 1]], dtype=int32)

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [70]:
arr17=np.random.randint(1,25,size=(5,5))

In [71]:
arr17

array([[12,  1,  9, 18, 11],
       [17,  7, 10,  3, 18],
       [ 2,  5, 14, 14,  4],
       [19, 24, 23,  6,  7],
       [23, 18,  4,  2, 14]], dtype=int32)

In [76]:
corner_elements = arr17[[0,4,0,4],[0,4,4,0]]

In [77]:
corner_elements

array([12, 14, 11, 23], dtype=int32)

In [78]:
arr18=np.random.randint(1,25,size=(5,5))

In [79]:
arr18

array([[ 4, 23,  3, 20, 10],
       [ 8,  4,  2,  9, 18],
       [10,  4, 24,  1, 18],
       [23, 15,  3, 20, 22],
       [ 5, 11, 12, 17, 17]], dtype=int32)

In [80]:
arr18[arr18>10]=10

In [81]:
arr18

array([[ 4, 10,  3, 10, 10],
       [ 8,  4,  2,  9, 10],
       [10,  4, 10,  1, 10],
       [10, 10,  3, 10, 10],
       [ 5, 10, 10, 10, 10]], dtype=int32)

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [82]:
#Define structure 

from numpy import dtype


dtype=[('name','U10'),
       ('age','i4'),
       ('Weight','f4')

]

In [84]:
people = np.array([
    ('Alice', 25, 55.5),
    ('Bob', 30, 72.0)
], dtype=dtype)


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [87]:
#Maksed array 

arr20=np.array([10,20,30,40,50])

masked=np.ma.masked_where(arr20 > 30,arr20)

In [88]:
masked

masked_array(data=[10, 20, 30, --, --],
             mask=[False, False, False,  True,  True],
       fill_value=999999)

In [89]:
arr21=np.random.randint(1,200,size=(4,4))

In [90]:
arr21

array([[ 11,  63,  99, 184],
       [135,  39, 123,  10],
       [121, 186, 179,  22],
       [139, 116,  43,  98]], dtype=int32)

In [91]:
masked=np.ma.masked_where(arr21 > 65,arr21)

In [92]:
masked

masked_array(
  data=[[11, 63, --, --],
        [--, 39, --, 10],
        [--, --, --, 22],
        [--, --, 43, --]],
  mask=[[False, False,  True,  True],
        [ True, False,  True, False],
        [ True,  True,  True, False],
        [ True,  True, False,  True]],
  fill_value=np.int64(999999),
  dtype=int32)

In [95]:
summation=np.sum(masked)

In [96]:
summation

np.int64(188)

In [97]:
from numpy import size


arr22=np.random.randint(1,100,size=(4,4))

In [99]:
arr22

array([[69, 78, 39,  2],
       [82, 74, 64, 40],
       [47, 44, 40, 37],
       [34, 75,  8, 67]], dtype=int32)

### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [3]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame(np.random.randint(1,100,size=(6,4)),
                columns=['A','B','C','D'])

In [8]:
df.set_index('A',inplace=True)

In [9]:
df

     B   C   D
A
74  22   8  51
85  58  35  34
67  88   8  81
50  29  65   7
45  57  46  99
94  57  86  33

In [13]:
#question 2 

df2=pd.DataFrame(np.random.randint(1,100,size=(3,3)),columns=['A','B','C'],index=['X','Y','Z'])

In [14]:
df2

    A   B   C
X  56  53  34
Y  74  63  93
Z  39  71  74

In [16]:
df2.loc['Y','B']

np.int32(63)

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [17]:
df3=pd.DataFrame(np.random.randint(1,100,size=(5,3)))

In [18]:
df3

    0   1   2
0  23  43  60
1   9  89  68
2  23  20  12
3  89  81  49
4  37  79   9

In [21]:
df3['NewColumn']=df3.iloc[:,0]*df3.iloc[:,1]

In [22]:
df3

    0   1   2  NewColumn
0  23  43  60        989
1   9  89  68        801
2  23  20  12        460
3  89  81  49       7209
4  37  79   9       2923

In [23]:
df4=pd.DataFrame(np.random.randint(1,100,size=(4,3)))

In [24]:
#Row sum 
row_sum=df4.sum(axis=1)

In [25]:
row_sum

0    151
1    117
2    159
3    221
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [28]:
df5=pd.DataFrame(np.random.randint(1,100,size=(5,3)),columns=['A','B','C'])

In [29]:
df5

    A   B   C
0   8  93  22
1   3  29  39
2  32  65  16
3  52  21  62
4  61  90   2

In [33]:
from math import nan


df5.iloc[0,1]=nan

In [34]:
df5

      A     B     C
0   8.0   NaN  22.0
1   3.0  29.0  39.0
2  32.0  65.0  16.0
3  52.0  21.0  62.0
4  61.0  90.0   2.0
0   NaN   NaN   NaN

In [37]:
df5.fillna(df5.mean(),inplace=True)

In [38]:
df5

      A      B     C
0   8.0  51.25  22.0
1   3.0  29.00  39.0
2  32.0  65.00  16.0
3  52.0  21.00  62.0
4  61.0  90.00   2.0
0  31.2  51.25  28.2

In [39]:
df6=pd.DataFrame(np.random.randint(1,100,size=(6,4)))

In [40]:
df6

    0   1   2   3
0  82  59  84  67
1  20  73  91   4
2  52  27  37  53
3  30  35  28  62
4  17  34   9  47
5  42  30  31  91

In [41]:
df6.iloc[0,1]=nan
df6.iloc[1,2]=nan

In [42]:
df6

    0     1     2   3
0  82   NaN  84.0  67
1  20  73.0   NaN   4
2  52  27.0  37.0  53
3  30  35.0  28.0  62
4  17  34.0   9.0  47
5  42  30.0  31.0  91

In [43]:
df6.dropna(inplace=True)

In [44]:
df6

    0     1     2   3
2  52  27.0  37.0  53
3  30  35.0  28.0  62
4  17  34.0   9.0  47
5  42  30.0  31.0  91

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [45]:
import pandas as pd
import numpy as np

# Number of rows
n = 10

# Create DataFrame
df = pd.DataFrame({
    'Category': np.random.choice(['A', 'B', 'C'], size=n),
    'Value': np.random.randint(1, 100, size=n)
})

print(df)

  Category  Value
0        B     57
1        B     32
2        B     90
3        A      9
4        A     97
5        A     90
6        B     21
7        C     93
8        C     63
9        A     30

In [47]:
df.groupby('Category')['Value'].agg(['sum','mean'])

          sum  mean
Category
A         226  56.5
B         200  50.0
C         156  78.0

In [48]:
import pandas as pd
import numpy as np

# Number of rows
n = 10

df = pd.DataFrame({
    'Product': np.random.choice(['Laptop', 'Phone', 'Tablet', 'Headphones'], size=n),
    'Category': np.random.choice(['Electronics', 'Accessories'], size=n),
    'Sales': np.random.randint(1000, 50000, size=n)
})

print(df)

      Product     Category  Sales
0  Headphones  Electronics   2284
1      Tablet  Electronics  18127
2      Laptop  Accessories   3785
3      Tablet  Electronics  18795
4      Laptop  Electronics  47505
5      Laptop  Electronics  13161
6      Tablet  Electronics  25534
7       Phone  Accessories  13588
8      Tablet  Accessories  40220
9       Phone  Accessories  21122

In [49]:
df.groupby(['Product','Category'])['Sales'].sum()

Product     Category
Headphones  Electronics     2284
Laptop      Accessories     3785
            Electronics    60666
Phone       Accessories    34710
Tablet      Accessories    40220
            Electronics    62456
Name: Sales, dtype: int32

In [50]:
import pandas as pd
import numpy as np

# First DataFrame
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': np.random.randint(20, 40, size=4)
})

# Second DataFrame (common column = 'ID')
df2 = pd.DataFrame({
    'ID': [2, 3, 4, 5],
    'Department': ['HR', 'IT', 'Finance', 'Marketing'],
    'Salary': np.random.randint(30000, 80000, size=4)
})

print("DataFrame 1:\n", df1)
print("\nDataFrame 2:\n", df2)

DataFrame 1:
    ID     Name  Age
0   1    Alice   33
1   2      Bob   27
2   3  Charlie   36
3   4    David   34

DataFrame 2:
    ID Department  Salary
0   2         HR   76049
1   3         IT   62938
2   4    Finance   69319
3   5  Marketing   31451

In [51]:
pd.merge(df1,df2,how='inner')

   ID     Name  Age Department  Salary
0   2      Bob   27         HR   76049
1   3  Charlie   36         IT   62938
2   4    David   34    Finance   69319

In [52]:
import pandas as pd
import numpy as np

# First DataFrame
df1 = pd.DataFrame({
    'A': np.random.randint(1, 50, 3),
    'B': np.random.randint(1, 50, 3)
})

# Second DataFrame (different columns)
df2 = pd.DataFrame({
    'C': np.random.randint(50, 100, 3),
    'D': np.random.randint(50, 100, 3)
})

print("DataFrame 1:\n", df1)
print("\nDataFrame 2:\n", df2)

# 🔹 Concatenate along rows (axis=0)
concat_rows = pd.concat([df1, df2], axis=0)
print("\nConcatenated along rows:\n", concat_rows)

# 🔹 Concatenate along columns (axis=1)
concat_cols = pd.concat([df1, df2], axis=1)
print("\nConcatenated along columns:\n", concat_cols)

DataFrame 1:
     A  B
0  44  2
1  38  1
2  23  8

DataFrame 2:
     C   D
0  86  64
1  57  66
2  84  66

Concatenated along rows:
       A    B     C     D
0  44.0  2.0   NaN   NaN
1  38.0  1.0   NaN   NaN
2  23.0  8.0   NaN   NaN
0   NaN  NaN  86.0  64.0
1   NaN  NaN  57.0  66.0
2   NaN  NaN  84.0  66.0

Concatenated along columns:
     A  B   C   D
0  44  2  86  64
1  38  1  57  66
2  23  8  84  66

In [ ]:
import pandas as pd
import numpy as np

# Create daily date range for 3 months
dates = pd.date_range(start='2025-01-01', periods=90, freq='D')

# Create DataFrame with datetime index
df = pd.DataFrame(
    {'Value': np.random.randint(10, 100, size=90)},
    index=dates
)

print("Original Daily Data:\n", df.head())

# Resample to monthly frequency and compute mean
monthly_mean = df.resample('M').mean()

print("\nMonthly Mean:\n", monthly_mean)

In [54]:
import pandas as pd
import numpy as np

# Create MultiIndex
arrays = [
    ['A', 'A', 'B', 'B'],
    [1, 2, 1, 2]
]

index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'Subcategory'))

# Create DataFrame
df = pd.DataFrame(
    np.random.randint(10, 100, size=(4, 2)),
    index=index,
    columns=['Value1', 'Value2']
)

print("MultiIndex DataFrame:\n", df)

MultiIndex DataFrame:
                       Value1  Value2
Category Subcategory
A        1                32      23
         2                74      19
B        1                21      88
         2                52      87

In [55]:
index=pd.MultiIndex.from_product(
    [['A','B'],[1,2,3]],
    names=['Category','SubCategory']
)

In [56]:
index

MultiIndex([('A', 1),
            ('A', 2),
            ('A', 3),
            ('B', 1),
            ('B', 2),
            ('B', 3)],
           names=['Category', 'SubCategory'])

In [57]:
#create data frame 
df=pd.DataFrame(
    np.random.randint(10,100,size=(6,2)),
    columns=['Value1','Value2'],
    index=index
)

In [58]:
df

                      Value1  Value2
Category SubCategory
A        1                82      66
         2                57      26
         3                91      71
B        1                42      93
         2                67      89
         3                20      89

In [59]:
df['Value1']

Category  SubCategory
A         1              82
          2              57
          3              91
B         1              42
          2              67
          3              20
Name: Value1, dtype: int32

In [61]:
df.loc['A',2]

Value1    57
Value2    26
Name: (A, 2), dtype: int32

In [62]:
#create multi index data frame

index=pd.MultiIndex.from_product(
    [['A','B','C'],['X','Y']],
    names=['Category','SubCategory']
)

In [63]:
index

MultiIndex([('A', 'X'),
            ('A', 'Y'),
            ('B', 'X'),
            ('B', 'Y'),
            ('C', 'X'),
            ('C', 'Y')],
           names=['Category', 'SubCategory'])

In [65]:
#create data frame with random values 

df=pd.DataFrame(
    np.random.randint(1,100,size=(6,2)),
    index=index
)

In [66]:
df

                       0   1
Category SubCategory
A        X            11  80
         Y            23  70
B        X            14  16
         Y            31  38
C        X            19  67
         Y            36  97

In [67]:
paisum=df.groupby(['Category','SubCategory']).sum()

In [68]:
paisum

                       0   1
Category SubCategory
A        X            11  80
         Y            23  70
B        X            14  16
         Y            31  38
C        X            19  67
         Y            36  97

In [69]:
df10=pd.DataFrame(np.random.randint(1,100,size=(5,3)))

In [70]:
df_doubled=df10.apply(lambda x:x*2)

In [71]:
df_doubled

     0   1    2
0   72   2   92
1  120  24  148
2  144  54   96
3  198  32   38
4  190  36   88

In [72]:
df10

    0   1   2
0  36   1  46
1  60  12  74
2  72  27  48
3  99  16  19
4  95  18  44

In [73]:
df10*2

     0   1    2
0   72   2   92
1  120  24  148
2  144  54   96
3  198  32   38
4  190  36   88

In [75]:



df10['total']=df10.apply(lambda row : row.sum(),axis=1)

In [76]:
df10

    0   1   2  total
0  36   1  46     83
1  60  12  74    146
2  72  27  48    147
3  99  16  19    134
4  95  18  44    157

In [77]:
words=['apple','banana']
df11=pd.Series(words)

In [78]:
df11

0     apple
1    banana
dtype: object

In [79]:
df11.str.upper()

0     APPLE
1    BANANA
dtype: object

In [80]:
first_three=df11.str[:3]

In [81]:
first_three

0    app
1    ban
dtype: object