 pandas is data manipulation library in python , widely used for data analysis and data cleaning 
 It provides two primary data structures : Series and data frame 

 Series : One dimensional array like objects

 
  
 Dataframe : Two dimensional , size mutable and heterogeneous data structure with labeled axes (rows and columns )

In [1]:
import pandas as pd

In [2]:
#Series 

#1-D array like object that can hold any data type 

import pandas as pd 
data =[1,2,3,4,5]
series=pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
#Create a series from dictionary 
data = {'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
series_dict

a    1
b    2
c    3
dtype: int64

In [5]:
data = [10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [6]:
#Create data frame from a dictionary of objects 

data = {
    'Name':['Debashis','Sahoo'],
    'Age':[24,25]
}
df=pd.DataFrame(data)

In [7]:
df

       Name  Age
0  Debashis   24
1     Sahoo   25

In [8]:
data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]

df1=pd.DataFrame(data)

In [9]:
df1

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [17]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [18]:
df.tail(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [19]:
#Accessing data from dataframe 
df['Product Name']

0                                        iPhone 14 Pro
1                                     Dyson V11 Vacuum
2                                     Levi's 501 Jeans
3                                    The Da Vinci Code
4                              Neutrogena Skincare Set
                            ...
235    Nespresso Vertuo Next Coffee and Espresso Maker
236                          Nike Air Force 1 Sneakers
237             The Handmaid's Tale by Margaret Atwood
238               Sunday Riley Luna Sleeping Night Oil
239                         Yeti Rambler 20 oz Tumbler
Name: Product Name, Length: 240, dtype: object

In [21]:
#loc selects data based on labels 
#iloc selects data based on index 

df.loc[:,"Product Category"]

0          Electronics
1      Home Appliances
2             Clothing
3                Books
4      Beauty Products
            ...
235    Home Appliances
236           Clothing
237              Books
238    Beauty Products
239             Sports
Name: Product Category, Length: 240, dtype: object

In [22]:
df.loc[0]

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object

In [23]:
df.iloc[1:3]

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card

In [ ]:
#Accessing a specific element 

#at - > label based , iat -> index based 
df.at[2,'Product Category']

'Clothing'

In [26]:
df.iat[2,2]

'Clothing'

In [27]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [28]:
df.iat[2,2]

'Bangalore'

In [29]:
df.iat[2,0]

'Bappy'

In [36]:
#Data manipulation with data frame 

#Adding a column 

df['Salary']=[50000,60000,70000,80000]

In [37]:
df

    Name  Age       City  Salary
0  Krish   32  Bangalore   50000
1   John   34  Bangalore   60000
2  Bappy   32  Bangalore   70000
3   JAck   32  Bangalore   80000

In [39]:
#Remove a column 
df.drop('Salary',axis=1,inplace=True)

In [35]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [40]:
#Add 1 to age column 

df['Age']+=1

In [41]:
df

    Name  Age       City
0  Krish   33  Bangalore
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   JAck   33  Bangalore

In [42]:
df1=pd.read_csv('sales_data.csv')

In [44]:
df1.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [45]:
#Display the data type of each column 

print(df.dtypes)

Name    object
Age      int64
City    object
dtype: object

In [47]:
df1.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [49]:
#Handling missing values 
df1.isnull().any()

Transaction ID      False
Date                False
Product Category    False
Product Name        False
Units Sold          False
Unit Price          False
Total Revenue       False
Region              False
Payment Method      False
dtype: bool

In [50]:
df2=pd.read_csv('data.csv')

In [51]:
df2.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [52]:
df.tail(5)

    Name  Age       City
0  Krish   33  Bangalore
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   JAck   33  Bangalore

In [58]:
df.isnull() #Detect missing values

    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [57]:
df.isna() #Detect missing values

    Name    Age   City
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [60]:
df2.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [62]:
df.dtypes

Name    object
Age      int64
City    object
dtype: object

In [63]:
df.describe()

        Age
count   4.0
mean   33.5
std     1.0
min    33.0
25%    33.0
50%    33.0
75%    33.5
max    35.0

In [66]:
df_filled=df2.fillna(0)

In [67]:
df2.head()

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [68]:
df2['Sales'].isnull().sum()

np.int64(4)

In [69]:
df2['Sales_filled']=df2['Sales'].fillna(df2['Sales'].mean())

In [71]:
df2.head()

         Date Category  Value   Product  Sales Region  Sales_filled
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [73]:
#Renaming column 

df2=df2.rename(columns={'Sales_filled':'Salesnew'})

In [75]:
df2.head()

         Date Category  Value   Product  Sales Region  Salesnew
0  2023-01-01        A   28.0  Product1  754.0   East     754.0
1  2023-01-02        B   39.0  Product3  110.0  North     110.0
2  2023-01-03        C   32.0  Product2  398.0   East     398.0
3  2023-01-04        B    8.0  Product1  522.0   East     522.0
4  2023-01-05        B   26.0  Product3  869.0  North     869.0

In [76]:
df2['New value']=df2['Value'].apply(lambda x:x**2)

In [77]:
df2.head()

         Date Category  Value   Product  Sales Region  Salesnew  New value
0  2023-01-01        A   28.0  Product1  754.0   East     754.0      784.0
1  2023-01-02        B   39.0  Product3  110.0  North     110.0     1521.0
2  2023-01-03        C   32.0  Product2  398.0   East     398.0     1024.0
3  2023-01-04        B    8.0  Product1  522.0   East     522.0       64.0
4  2023-01-05        B   26.0  Product3  869.0  North     869.0      676.0

In [79]:
#Data Aggregating and grouping 
grouped_mean = df2.groupby('Product')['Value'].mean()

In [80]:
grouped_mean

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [81]:
data = df2.groupby(['Product','Region'])['Value'].mean()

In [82]:
data

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [83]:
### Merging and joining Dataframes
# Create sample DataFrames
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [84]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [85]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [88]:
pd.merge(df1,df2,how="inner",on="Key")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [89]:
pd.merge(df1,df2,how="left",on="Key")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN